/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.96.1
*/

export { Registrar } from './Registrar';
export { RegistrarFactory } from './RegistrarFactory';
export { Registry } from './Registry';
export { RegistryFactory } from './RegistryFactory';
export { Resolver } from './Resolver';
export { ResolverFactory } from './ResolverFactory';
